### ISSUE TITLE
Switch length suffix to snake_case

### ISSUE THREAD

**Issue by lucasvo** [centrifuge/precise-proofs#40]
`snake_case` is the protobuf standard for field names, therefore we should change the default length suffix to `_length` instead of `Length`

**Comment by lucasvo** [comment]
This change was done, but the variable name is confusing, DefaultSaltsLenghtSuffix is not actually used with salts anymore.

**Comment by zyfrank** [comment]
Actually, I think may be the name can be "DefaultLengthName", because it contains no salt and it is not suffix anymore,

If you think this is a right choice, I can make a PR quickly

________________________________
发件人: Lucas Vogelsang <notifications@github.com>
发送时间: 2019年1月18日 11:00
收件人: centrifuge/precise-proofs
抄送: Subscribed
主题: Re: [centrifuge/precise-proofs] Switch length suffix to snake_case (#40)


This change was done, but the variable name is confusing, DefaultSaltsLenghtSuffix is not actually used with salts anymore.

―
